-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Feb 04, 2020 at 07:51 PM
-- Server version: 5.6.44-cll-lve
-- PHP Version: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `winnie`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `category_name` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `category_name`) VALUES
(2, 'j hooks'),
(3, 'bridle rings'),
(4, 'grommets'),
(5, 'd rings'),
(6, 'magnetic products'),
(7, 'stainless steel'),
(8, 'beam clamps'),
(9, 'j hook trees'),
(10, 'ceiling brackets'),
(11, 'grip tape'),
(12, 'misc clips');

-- --------------------------------------------------------

--
-- Table structure for table `members`
--

CREATE TABLE `members` (
  `id` int(11) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `members`
--

INSERT INTO `members` (`id`, `full_name`, `email`, `password`) VALUES
(1, 'Jon Winnie', 'jwinnie@winnieindustries.com', 'a92f2418fb7a402879ffa1127f6bc408');

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_description` longtext NOT NULL,
  `product_category` varchar(255) NOT NULL,
  `product_image` varchar(255) NOT NULL,
  `product_attachment` varchar(255) NOT NULL,
  `popular` varchar(255) NOT NULL,
  `new_product` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `product_name`, `product_description`, `product_category`, `product_image`, `product_attachment`, `popular`, `new_product`) VALUES
(9, '3/4â€ J Hook', '<p>3/4&rdquo; Data Cabling J Hook</p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 Cat 5/5e, or 16 Fiber Optic,<br />\r\n	or 10 Cat 6 Cables, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '3', 'uploads/5ce450dbdd152.jpeg', 'uploads/5b20289d65f7d.pdf', 'yes', 'no'),
(10, '1 5/16â€ J Hook', '<p>1 5/16&rdquo; Cata Cabling J Hook</p>\r\n\r\n<p>Item# WJH21</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>50 Cat 5/5e, or 50 Fiber Optic,<br />\r\n	or 30 Cat 6 Cables, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '3', 'uploads/5ce452347aa29.jpeg', 'uploads/5b20284ccca2d.pdf', 'no', 'no'),
(11, '2â€ J Hook', '<h2>Product Description :</h2>\r\n\r\n<p>2&rdquo; Data Cabling J Hook</p>\r\n\r\n<p>Item# WJH32</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>80 Cat 5/5e, or 80 Fiber Optic,<br />\r\n	or 50 Cat 6 Cable, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '3', 'uploads/5ce4536fa900a.jpeg', 'uploads/5b29192d2f270.pdf', 'no', 'no'),
(12, '4â€ J Hook', '<p>4&Prime; Data J Hook</p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 Cat 5/5e, or 300 Fiber Optic,<br />\r\n	or 185 Cat 6 Cable, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '3', 'uploads/5ce4538392875.jpeg', 'uploads/5b291ae7c48e3.pdf', 'no', 'no'),
(15, '1/4â€ Bridle Ring 1/4-20 Thread', '<p>1/4&rdquo; Bridal Ring 1/4-20 Thread</p>\r\n', '15', 'uploads/5b0fdafc6d495.png', '', 'no', 'no'),
(16, '2â€ Bridle Ring Â¼-20 Thread', '<p>2&rdquo; Bridal Ring &frac14;-20 Thread</p>\r\n', '16', 'uploads/5b0fdb1967ba4.png', '', 'yes', 'no'),
(17, '2â€ D Rings', '<p><strong>2&Prime; Distribution Rings</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WDR200</p>\r\n\r\n<p><strong>Std Box Qty:</strong>&nbsp;50</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a die cast aluminum for holding wires and cables for strength and durability. &nbsp;Can be used in cable terminals, ceilings, floors, walls, etc. &nbsp;Rounded, smooth edges prevent damage to cable insulation and jackets</p>\r\n', '12', 'uploads/5b0fddf276c78.png', 'uploads/5b30e43fb3e81.pdf', 'yes', 'no'),
(18, '16 lb Magnetic Cable Tie Mount â€“ Black', '<p>16 lb Magnetic Cable Tie Mount &ndash; Black</p>\r\n', '13', 'uploads/5b0fdeab30105.png', '', 'yes', 'no'),
(19, '26 lb Magnetic Cable Tie Mount â€“ White', '<p>26 lb Magnetic Cable Tie Mount &ndash; White</p>\r\n', '13', 'uploads/5b0fdecd523b3.png', '', 'no', ''),
(20, '24â€ Heavy Duty T-Bar Mount', '<p>24&Prime; Heavy Duty T-Bar Mount</p>\r\n\r\n<p><strong>Part #</strong>&nbsp; W512HD</p>\r\n\r\n<p><strong>Std. Box Qty.</strong>&nbsp;25</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>24&Prime; Heavy Duty T-Bar Mount can mount 1-1/2&Prime; or 2 1/8&Prime; boxes securely to the T-Bar.</p>\r\n', '14', 'uploads/5b0fdfcaa39be.png', '', 'no', 'no'),
(21, 'Angle Bracket Extension', '<p>Angle Bracket Extension</p>\r\n', '15', 'uploads/5b0fdfde895c8.png', '', 'no', ''),
(22, 'Hammer on 1/8â€ to 1/4â€ Flange, 1/4â€ Hole', '<p>Hammer on 1/8&rdquo; to 1/4&rdquo; Flange, 1/4&rdquo; Hole</p>\r\n', '16', 'uploads/5b0fe16973d9f.png', '', 'no', ''),
(24, '3/4\" J HOOK W/ 90 DEG ANGLE CLIP', '<p><strong>3/4&Prime; Data J Hook with 90&deg; Angle Clip</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12AC</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Angle Clip has a &frac14;&rdquo; Hole for screws and nails</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 2-strand fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '4', 'uploads/5ce455090d060.jpeg', 'uploads/5df8ce9013248.pdf', 'no', 'no'),
(25, '1 5/16â€ J Hook w/ 90 Deg Angle Clip', '<p><strong>1 5/16&rdquo; Data J Hook with 90&deg; Angle Clip</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21AC</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>Angle Clip has a &frac14;&rdquo; Hole for screws and nails</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '4', 'uploads/5ce4558bc0b44.jpeg', 'uploads/5b291ebb13a62.pdf', 'no', 'no'),
(26, '2\" J HOOK W/ 90 DEG ANGLE CLIP', '<p><strong>2&rdquo; Data&nbsp;</strong><strong>J Hook with 90&deg; Angle Clip</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32AC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre Galvanized Steel</li>\r\n	<li>Angle Clip has a &frac14;&rdquo; Hole for screws and nails</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50&nbsp;Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '4', 'uploads/5ce455e258536.jpeg', 'uploads/5b2920dbd0037.pdf', 'no', 'no'),
(27, '4\" J HOOKS W/ 90 DEG ANGLE CLIP', '<p><strong>4&Prime; Data J Hook with 90&deg; Angle Clip</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64AC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Angle Clip has a &frac14;&rdquo; Hole for screws and nails</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '4', 'uploads/5ce45499b8f90.jpeg', 'uploads/5b2923bc6eccc.pdf', 'no', 'no'),
(28, '3/4\" J HOOK W/ BATWING', '<p><strong>3/4&Prime; Data J Hook with Batwing</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12W</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Fastens to 12 gauge wire (pencil rod) or threaded rod up to 3/8&rdquo; in diameter</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Compare to: CADDY&rsquo;S&reg; CAT124Z34 / B-LINE&rsquo;S&reg; BCH12-W2 / PANDUIT&rsquo;S&reg; JP75DW-L20</p>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '5', 'uploads/5ce456a1925c1.jpeg', 'uploads/5df8cc533b844.pdf', 'no', 'no'),
(29, '1 5/16\" J HOOK W/ BATWING', '<p><strong>1 5/16&rdquo; Data J Hook with Batwing</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21W</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>Fastens to 12 gauge wire (pencil rod) or threaded rod up to 3/8&rdquo; in diameter</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '5', 'uploads/5ce456f9b7ca6.jpeg', 'uploads/5b29398da73a8.pdf', 'no', 'no'),
(30, '2 J HOOK W/ BATWING', '<p><strong>2&rdquo; Data J Hook with Batwing</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32W</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre Galvanized Steel</li>\r\n	<li>Fastens to 12 gauge wire (pencil rod) or threaded rod up to 3/8&rdquo; in diameter</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '5', 'uploads/5ce4575962c07.jpeg', 'uploads/5b29396e97669.pdf', 'no', 'no'),
(31, '4 J HOOK W/ BATWING', '<p><strong>4&Prime; Data J Hook with Batwing</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64W</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Fastens to 12 gauge wire (pencil rod) or threaded rod up to 3/8&rdquo; in diameter</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '5', 'uploads/5ce457801e888.jpeg', 'uploads/5e132ec1a5c95.pdf', 'no', 'no'),
(32, '3/4\" J Hook W/ PRESSED BEAM CLAMP', '<p>3/4&quot; Data J Hook w/ Pressed Beam Clamp</p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12PBC</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel J Hook</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Screwed on pressed steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '6', 'uploads/5ce45867ec719.jpeg', 'uploads/5df8d46313111.pdf', 'no', 'no'),
(33, '1 5/16\" J HOOK W/ PRESSED BEAM CLAMP', '<p><strong>1 5/16&rdquo; Data J Hook with Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21PBC</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '6', 'uploads/5ce458e74999c.jpeg', 'uploads/5e12263424912.pdf', 'no', 'no'),
(34, '2\" J HOOK W/ PRESSED BEAM CLAMP', '<p><strong>2&rdquo; Data&nbsp;</strong><strong>J Hook with Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32PBC</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '6', 'uploads/5ce4593646713.jpeg', 'uploads/5e1287390235f.pdf', 'no', 'no'),
(35, '4\" J HOOK W/ PRESSED BEAM CLAMP', '<p><strong>4&Prime; Data J Hook with Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64PBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '6', 'uploads/5ce4597e2220d.jpeg', 'uploads/5e1330f72637a.pdf', 'no', 'no'),
(36, '3/4\" J HOOK W/ 360 DEG PRESSED BEAM CLAMP', '<h2>Product Description :</h2>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>3/4&quot; Data J Hook w/ 360 Deg Pressed Beam Clamp</p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12ACPBC</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel J Hook</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Screwed on pressed steel beam clamp to angle clip to position 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '17', 'uploads/5ce46b42023ca.jpeg', 'uploads/5df8e243155bb.pdf', 'no', 'no'),
(37, '1 5/16\" J HOOK W/ 360 DEG PRESSED BEAM CLAMP', '<p><strong>1 5/16&rdquo; Data J Hook with 360 Degree Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACPBC</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp, position 360 Degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '17', 'uploads/5ce55490f0834.jpeg', 'uploads/5e1246cf8b1be.pdf', 'no', 'no'),
(38, '2â€ J Hook w/ 360 Deg Pressed Beam Clamp', '<p><strong>2&rdquo; Data&nbsp;</strong><strong>J Hook with 360 Deg Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACPBC</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp, postion 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '17', 'uploads/5ce554f39f900.jpeg', 'uploads/5e128a5dddd8b.pdf', 'no', 'no'),
(39, '4â€³ J Hook w/ 360 Deg Pressed Beam Clamp', '<p><strong>4&Prime; Data J Hook with 360 Degree Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACPBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Screwed on pressed steel beam clamp, positionable 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '17', 'uploads/5ce463ecdcc81.jpeg', 'uploads/5e1333ad9489d.pdf', 'yes', 'no'),
(40, '3/4\" J HOOK W/ HAMMER 1/8\" TO 1/4\" FLANGE', '<p><strong>3/4&Prime; Data J Hook with Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12HOK24</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Hammer on Clip for 1/8&rdquo; to &frac14;&rdquo; Flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '7', 'uploads/5ce464691125f.jpeg', 'uploads/5df8d25b72dad.pdf', 'no', 'no'),
(41, '1 5/16\" J HOOK W/ HAMMER 1/8\" TO 1/4\" FLANGE', '<p><strong>1 5/16&rdquo; Data J Hook with Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21HOK24</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '7', 'uploads/5ce464e5ad220.jpeg', 'uploads/5e12169fe9769.pdf', 'no', 'no'),
(42, '2â€ J Hook w/ Hammer 1/8â€ to Â¼â€ Flange', '<p><strong>2&rdquo; Data&nbsp;J Hook with Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32HOK24</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '7', 'uploads/5ce465fb80a3c.jpeg', 'uploads/5e1285e2726d3.pdf', 'no', 'no'),
(43, '4â€³ J Hook w/ Hammer 1/8â€ to Â¼â€ Flange', '<p><strong>4&Prime; Data J Hook with Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64HOK24</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; Flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '7', 'uploads/5ce4665270363.jpeg', 'uploads/5e132fb7e2a06.pdf', 'no', 'no'),
(44, '3/4â€³ J Hook w/ Hammer 5/16â€ to Â½â€ Flange', '<p><strong>3/4&Prime; Data J Hook with Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12HOK58</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Hammer on Clip for 5/16&rdquo; to &frac12;&rdquo; Flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '8', 'uploads/5ce4675009ebf.jpeg', 'uploads/5df8d357721a9.pdf', 'no', 'no'),
(45, '1 5/16â€ J Hook w/ Hammer 5/16â€ to Â½â€ Flange', '<p><strong>1 5/16&rdquo; Data J Hook with Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21HOK58</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 5/16&rdquo; to &frac12;&rdquo; Flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '8', 'uploads/5ce46793e4279.jpeg', 'uploads/5e1224478fd0c.pdf', 'no', 'no'),
(46, '2â€Â J Hook with Hammer 5/16â€ to Â½â€ Flange', '<p><strong>2&rdquo; Data&nbsp;</strong><strong>J Hook with Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32HOK58</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Hammer on clip for 5/16&rdquo; to &frac12;&rdquo; flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '8', 'uploads/5ce80642927f6.jpeg', 'uploads/5e12869650329.pdf', 'no', 'no'),
(47, '4â€³ J Hook w/ Hammer 5/16â€ to Â½â€ Flange', '<p><strong>4&Prime; Data J Hook with Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64HOK58</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 5/16&rdquo; to &frac12;&rdquo; flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '8', 'uploads/5ce4681a4a06e.jpeg', 'uploads/5e13305933952.pdf', 'no', 'no'),
(48, '3/4â€³ J Hook with 360 Hammer 5/16â€ to Â½â€ Flange', '<p><strong>3/4&Prime; J Hook with 360 Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12ACM58</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Hammer on Clip for 5/16&rdquo; to &frac12;&rdquo; Flanges</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '18', 'uploads/5ce555933408f.jpeg', 'uploads/5df8e09eacfae.pdf', 'no', 'no'),
(49, '1 5/16â€ J HOOK W/ 360 DEG HAMMER 5/16â€ TO Â½â€ FLANGE', '<p><strong>1 5/16&rdquo; Data J Hook with 360 Degree&nbsp;Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACM58</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>Hammer on Clip for 5/16&rdquo; to &frac12;&rdquo; Flanges, Can move around 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '18', 'uploads/5ce556b828ebd.jpeg', 'uploads/5e12457472507.pdf', 'no', 'no'),
(50, '2â€ J HOOK W/ 360 DEG HAMMER 5/16â€ TO Â½â€ FLANGE', '<p><strong>2&rdquo; Data&nbsp;J Hook with 360 Degree Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACM58</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Hammer on clip 5/16&rdquo; to &frac12;&rdquo; flanges, position able 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity</strong><strong>:</strong>&nbsp;100</p>\r\n', '18', 'uploads/5ce55adbef8b1.jpeg', 'uploads/5e1289893299a.pdf', 'no', 'no'),
(51, '4â€³ J Hook w/ 360 Deg Hammer 5/16â€ to Â½â€ Flange', '<p><strong>4&Prime; Data J Hook with 360 Degree Hammer 5/16&rdquo; to &frac12;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACM58</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 5/16&rdquo; to &frac12;&rdquo; flanges, position up to 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '18', 'uploads/5ce55b08e09bf.jpeg', 'uploads/5e133304e3944.pdf', 'no', 'no'),
(52, '3/4\" J HOOK W/ 360 DEG HAMMER 1/8\" TO 1/4\" FLANGE', '<p><strong>3/4&Prime; Data J Hook with Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12ACM24</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Hammer on Clip for 1/8&rdquo; to &frac14;&rdquo; Flanges, Positionable 360 Degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '19', 'uploads/5ce55ca344605.jpeg', 'uploads/5df8dfd8590bf.pdf', 'no', 'no'),
(53, '1 5/16\" J HOOK W/ 360 DEG HAMMER 1/8\" TO 1/4\" FLANGE', '<p><strong>1 5/16&rdquo; Data J Hook with 360 Degree Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACM24</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; Flanges, positionable 360 Degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '19', 'uploads/5ce55d1652bd4.jpeg', 'uploads/5e1228be91bf1.pdf', 'no', 'no'),
(54, '2\" J HOOK W/ 360 DEG HAMMER ON 1/8\" TO 1/4\" FLANGE', '<p><strong>2&rdquo; Data&nbsp;</strong><strong>J Hook with 360 Degree Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACM24</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges, postionable 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '19', 'uploads/5ce55d68d8e8a.jpeg', 'uploads/5e1288b4e772b.pdf', 'no', 'no'),
(55, '4â€³ Data J Hook with 360 Deg Hammer 1/8â€ to Â¼â€ Flange', '<p><strong>4&Prime; Data J Hook with 360 Deg Hammer 1/8&rdquo; to &frac14;&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACM24</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges, position up to 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '19', 'uploads/5ce55db38ec85.jpeg', 'uploads/5e1332404e057.pdf', 'no', 'no'),
(56, '3/4â€³ J Hook with Stamped Steel Beam Clamp', '<p><strong>3/4&Prime; J Hook with Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12SSBC</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel J Hook</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Screwed on stamped steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '20', 'uploads/5ce8070c51f5d.jpeg', 'uploads/5df8dee19fedd.pdf', 'no', 'no'),
(57, '1 5/16â€ J Hook with Stamped Steel Beam Clamp', '<p><strong>1 5/16&rdquo; J Hook with Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21SSBC</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Screwed on stamped steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '20', 'uploads/5ce807593de70.jpeg', 'uploads/5e122721e8695.pdf', 'no', 'no'),
(58, '2â€Â J Hook with Stamped Steel Beam Clamp', '<p><strong>2&rdquo;&nbsp;</strong><strong>J Hook with Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32SSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Screwed on stamped steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '20', 'uploads/5ce80795a0504.jpeg', 'uploads/5e1287fe0c833.pdf', 'no', 'no'),
(59, '4â€³ J Hook with Stamped Steel Beam Clamp', '<p><strong>4&Prime; J Hook with Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64SSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Screwed on stamped steel beam clamp</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '20', 'uploads/5ce808427e671.jpeg', 'uploads/5e133197a4d81.pdf', 'no', 'no'),
(60, '3/4â€³ J Hook w/ 360 Deg Stamped Steel Beam Clamp', '<p><strong>3/4&Prime; J Hook with Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12ACSSBC</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel J Hook</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Screwed on stamped steel beam clamp, postionable 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '21', 'uploads/5ce809949aab7.jpeg', 'uploads/5df8e6b904639.pdf', 'no', 'no'),
(61, '1 5/16â€ J Hook w/ 360 Deg Stamped Steel Beam Clamp', '<p><strong>1 5/16&rdquo; J Hook with 360 degree Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACSSBC</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy Duty Pre-galvanized Steel</li>\r\n	<li>Screwed on stamped steel beam clamp, postionable 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '21', 'uploads/5ce809a4d0b87.jpeg', 'uploads/5e127945ea130.pdf', 'no', 'no'),
(62, '2â€Â J Hook w/ 360 Deg Stamped Steel Beam Clamp', '<p><strong>2&rdquo;&nbsp;</strong><strong>J Hook with 360 Degree Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACSSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Pre galvanized steel</li>\r\n	<li>Screwed on stamped steel beam clamp, position 360 degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n', '21', 'uploads/5ce809b6c4ac9.jpeg', 'uploads/5e128d4f66c9b.pdf', 'no', 'no'),
(63, '4â€³ J Hook w/ 360 Deg Stamped Steel Beam Clamp', '<p><strong>4&Prime; J Hook with 360 Degree Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACSSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Screwed on stamped steel beam clamp, position up to 360 Degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '21', 'uploads/5ce809c7df972.jpeg', 'uploads/5e13366b647d2.pdf', 'no', 'no'),
(64, '1 1/4\" Bridle Ring, 1/4-20 Thread', '<p><strong>1 1/4&quot; Bridle Ring with 1/4-20 Thread</strong></p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WBR4T125</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1.25&Prime; Diameter ring</li>\r\n	<li>1.5&Prime; threaded 1/4-20 stand off, as required by the NEC</li>\r\n</ul>\r\n', '9', 'uploads/5b30d8bb84383.jpeg', '', 'no', 'no'),
(65, '2â€ Bridle Ring 1/4-20 Thread', '<p><strong>2&rdquo; Bridle Ring 1/4-20 Thread</strong></p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WBR4T200</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Diameter ring</li>\r\n	<li>1.5&Prime; threaded 1/4-20 stand off, as required by the NEC</li>\r\n</ul>\r\n', '9', 'uploads/5b30d9e9a1412.jpeg', '', 'no', 'no'),
(66, '4â€³ Bridle Ring w/ 1/4-20 Thread', '<p>4&Prime; Bridle Ring w/ 1/4-20 Thread</p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WBR4T400</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Diameter ring</li>\r\n	<li>1.5&Prime; threaded 1/4-20 stand off, as required by the NEC</li>\r\n</ul>\r\n', '9', 'uploads/5b30da0a73b63.jpeg', '', 'no', 'no'),
(67, '1 1/4â€³ Wood Screw Bridle Ring', '<p>1 1/4&Prime; Wood Screw Bridle Ring</p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WBR125WS</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1.25&Prime; Diameter ring</li>\r\n	<li>1.5&Prime; stand off, as required by the NEC with wood screwing threads</li>\r\n</ul>\r\n', '10', 'uploads/5b30dc4ad349d.jpeg', '', 'no', 'no'),
(68, '2â€³ Wood Screw Bridle Ring', '<h1>2&Prime; Wood Screw Bridle Ring</h1>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WBR200WS</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Diameter ring</li>\r\n	<li>1.5&Prime; stand off, as required by the NEC with wood screwing threads</li>\r\n</ul>\r\n', '10', 'uploads/5b30dc6bd9323.jpeg', '', 'no', 'no'),
(69, '1 1/4â€³ Bridle Ring w/ Nail', '<h1>1 1/4&Prime; Bridle Ring w/ Nail</h1>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WACTBR125</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can fit a Ramset, Hilti, and Powers nail guns. &nbsp;Equipped with a .300 x 1-1/4&quot; pin in a 90&deg; angle clip</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1.25&Prime; Diameter ring</li>\r\n	<li>1/4-20 threaded ring preassembled to eyelet</li>\r\n	<li>Nail already preloaded for shooting into various surfaces</li>\r\n</ul>\r\n', '11', 'uploads/5b30de7b84552.jpeg', '', 'no', 'no'),
(70, '2â€³ Bridle Ring w/ Nail', '<p><strong>2&Prime; Bridle Ring w/ Nail</strong></p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WACTBR200</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can fit a Ramset, Hilti, and Powers nail guns. &nbsp;Equipped with a .300 x 1-1/4&quot; pin in a 90&deg; angle clip</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Diameter ring</li>\r\n	<li>1/4-20 threaded ring preassembled to eyelet</li>\r\n	<li>Nail already preloaded for shooting into various surfaces</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n', '11', 'uploads/5b30de9d8dcd7.jpeg', '', 'no', 'no'),
(71, '4â€³ Bridle Ring w/ Nail', '<p><strong>4&Prime; Bridle Ring w/ Nail</strong></p>\r\n\r\n<p><strong>Part Number:</strong>&nbsp; WACTBR400</p>\r\n\r\n<p><strong>Std. Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can fit a Ramset, Hilti, and Powers nail guns. &nbsp;Equipped with a .300 x 1-1/4&quot; pin in a 90&deg; angle clip</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Diameter ring</li>\r\n	<li>1/4-20 threaded ring preassembled to eyelet</li>\r\n	<li>Nail already preloaded for shooting into various surfaces</li>\r\n</ul>\r\n', '11', 'uploads/5b30decc2be16.jpeg', '', 'no', 'no'),
(72, '3\" D Ring', '<p><strong>3&Prime; Distribution Rings</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WDR300</p>\r\n\r\n<p><strong>Std Box Qty:</strong>&nbsp;50</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a die cast aluminum for holding wires and cables for strength and durability. &nbsp;Can be used in cable terminals, ceilings, floors, walls, etc. &nbsp;Rounded, smooth edges prevent damage to cable insulation and jackets</p>\r\n', '12', 'uploads/5b30e3e53565e.jpg', 'uploads/5b30e4663db89.pdf', 'no', 'no'),
(73, '5â€³ Distribution Rings', '<p><strong>5&Prime; Distribution Rings</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WDR500</p>\r\n\r\n<p><strong>Std Box Qty:</strong>&nbsp;50</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a die cast aluminum for holding wires and cables for strength and durability. &nbsp;Can be used in cable terminals, ceilings, floors, walls, etc. &nbsp;Rounded, smooth edges prevent damage to cable insulation and jackets</p>\r\n', '12', 'uploads/5b30e416abdb9.jpg', 'uploads/5b30e416abdf6.pdf', 'no', 'no'),
(74, '3/4\" Magnetic Bridle Ring', '<p><strong>3/4&quot; Magnetic Bridle Ring</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBRL075MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet with a 1.5&Prime; stand off. &nbsp;3/4&Prime; Diameter ring for securing wires and cables.</p>\r\n', '26', 'uploads/5b30f38b1d61b.jpeg', '', 'no', 'no'),
(75, '1 1/4\" Magnetic Bridle Ring, 1.5\" standoff', '<p><strong>Part #</strong>&nbsp;WBRL125MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet with a 1 1/4&Prime; Diameter ring for securing wires and cables. &nbsp;Can hold up to 107 lbs against 3mm or thicker metal.</p>\r\n', '26', 'uploads/5b30f3dc5faf6.jpeg', '', 'no', 'no'),
(76, '2\" Magnetic Bridle Ring', '<p><strong>2&quot; Magnetic Bridle Ring</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBRL200MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet with a 2&Prime; Diameter ring for securing wires and cables. &nbsp;Can hold up to 107 lbs against 3mm or thicker metal.</p>\r\n', '26', 'uploads/5b30f43b6fd8c.jpeg', '', 'no', 'no'),
(77, '3/4\" Magnetic Bridle Ring, short stem', '<p><strong>3/4&quot; Magnetic Bridle Ring, Short Post</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR075MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet. &nbsp;3/4&Prime; Diameter ring for securing wires and cables.</p>\r\n', '26', 'uploads/5b30f73e46a87.jpeg', '', 'no', 'no'),
(78, '1 1/4\" Magnetic Bridle Ring, Short Standoff', '<p><strong>1 1/4&quot; Magnetic Bridle Ring, Short Standoff</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR125MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet with a 1 1/4&Prime; Diameter ring for securing wires and cables. &nbsp;Can hold up to 107 lbs against 3mm or thicker metal.</p>\r\n', '26', 'uploads/5b30f68520511.jpeg', '', 'no', 'no'),
(79, '2\" Magnetic Bridle Ring, short post', '<p><strong>2&quot; Magnetic Bridle Ring, Short Post</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR200MAG</p>\r\n\r\n<p><strong>Std Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features a permanent rare earth magnet with a 2&Prime; Diameter ring for securing wires and cables. &nbsp;Can hold up to 107 lbs against 3mm or thicker metal.</p>\r\n', '26', 'uploads/5b30f6bd6acf0.jpeg', '', 'no', 'no'),
(80, '1/4-20 Mounting Magnet', '<p><strong>1/4-20 Mounting Magnet</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WMAG1420F</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Screw stopping feature</li>\r\n	<li>up to 107 lb pull strength (against 3mm or thicker metal)</li>\r\n	<li>Permanent rare earth magnet</li>\r\n</ul>\r\n\r\n<p><strong>Benefits:</strong></p>\r\n\r\n<ul>\r\n	<li>Thin profile helps eliminate a &ldquo;tipping&rdquo; action</li>\r\n	<li>Can be used in lots of areas; industrial, electrical, construction, etc.</li>\r\n	<li>Nickel plated for a higher corrosion resistance</li>\r\n</ul>\r\n\r\n<p><strong>Standard Box Qty: 100</strong></p>\r\n\r\n<p><em>Patent pending</em></p>\r\n', '27', 'uploads/5b30f82c46263.jpg', 'uploads/5b30f82c462a2.pdf', 'no', 'no'),
(81, 'Pressed Beam Clamp', '<p><strong>1/4-20 Threaded Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp; WPBC</p>\r\n\r\n<p><strong>Std Box Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>This beam clamp has a 1/4-20 thread on the side and bottom. &nbsp;Thick steel, and has teeth to help grip onto the beams.</p>\r\n', '28', 'uploads/5b30fcfb8481a.jpg', '', 'yes', 'yes'),
(82, 'Hammer on 1/8-1/4â€³, 1/4-20 Thread', '<p>Hammer on 1/8-1/4&Prime;Flange, Keyed 1/4-20 Thread on side and bottom</p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WM24</p>\r\n\r\n<p><strong>Std. Box Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can hammer onto 1/8&Prime; to 1/4&Prime; Flanges. &nbsp;Has 1/4-20 threads, and slots for a standard 50 lb tensile strength cable tie.</p>\r\n', '28', 'uploads/5b324f3839cfd.jpg', '', 'no', 'no'),
(83, 'Hammer on 5/16\"-1/2\", 1/4-20 Thread', '<p><strong>Hammer on 5/16&quot;-1/2&quot; Flange, 1/4-20 Thread</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WM58</p>\r\n\r\n<p><strong>Std. Box Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can hammer onto 5/16&Prime; to 1/2&Prime; Flanges. &nbsp;Has 1/4-20 threads, and slots for a standard 50 lb tensile strength cable tie.</p>\r\n', '28', 'uploads/5b324f863fd92.jpg', '', 'no', 'no'),
(84, 'Batwing/ Multifunction Clip', '<h1>Batwing/ Multifunction Clip</h1>\r\n\r\n<p>Part # WBW34</p>\r\n\r\n<p>Std. Box Qty: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>This multifunction clip can fit on pencil rod all the way up too 3/8&Prime; All threaded rod. &nbsp;Has 1/4-20 and 10-24 keyed thread holes, and a 1/4&Prime; hole.</p>\r\n', '28', 'uploads/5b32541feb83d.jpg', '', 'no', 'no'),
(85, 'Spring Steel Beam Clamp', '<p><strong>Part #</strong>&nbsp;WSSBC</p>\r\n\r\n<p><strong>Std. Box Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>This beam clamp has a Keyed 1/4-20 thread on the side and bottom. &nbsp;The side also has a 10-24 thread. &nbsp;The screw can fit a philips screw driver or a standard hex wrench.</p>\r\n', '28', 'uploads/5b32543cd8e8a.jpg', '', 'no', 'no'),
(86, 'Hammer on 1/8â€³-1/4â€³ Flange, 1/4â€³ Hole', '<p>Hammer on 1/8&Prime;-1/4&Prime; Flange, 1/4&Prime; Hole</p>\r\n\r\n<p>Part #&nbsp; WHOK-24</p>\r\n\r\n<p>Std Box QTY: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can be used to attached to J Hooks, secure jack chain, ceiling wire(pencil rod), etc.</p>\r\n', '28', 'uploads/5b32546a921ab.jpg', '', 'no', 'no'),
(87, 'Hammer on 5/16â€³-1/2â€³ Flange, 1/4â€³ Hole', '<h1>Hammer on 5/16&Prime;-1/2&Prime; Flange, 1/4&Prime; Hole</h1>\r\n\r\n<p><strong>Part #</strong>&nbsp; WHOK-58</p>\r\n\r\n<p><strong>Std Box QTY:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Can be used to attached to J Hooks, secure jack chain, ceiling wire(pencil rod), etc.</p>\r\n', '28', 'uploads/5b3254834fa7a.jpg', '', 'no', 'no'),
(88, '1/4-20 Malleable Beam Clamp', '<h1>1/4-20 Malleable Beam Clamp</h1>\r\n\r\n<p><strong>Part #</strong>&nbsp; WMBC4T</p>\r\n\r\n<p><strong>Std. Box Qty:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>3/4&Prime; Jaw Opening, and 1/4-20 threads on top and bottom.</p>\r\n', '28', 'uploads/5b3254c97de32.jpg', '', 'no', 'no'),
(89, '24â€³ T Bar Mount Adjust to 8â€³', '<h1>24&Prime; T Bar Mount Adjust to 8&Prime;</h1>\r\n\r\n<p><strong>Part #</strong>&nbsp; W512A</p>\r\n\r\n<p><strong>Std. Box Qty.</strong>&nbsp;50</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>24&Prime; wing span T-Bar Mount can mount boxes securely to the T-Bar and adjusts up to 8&Prime; for the deeper boxes.</p>\r\n', '14', 'uploads/5b3256fab6ada.jpg', '', 'no', 'no');
INSERT INTO `products` (`id`, `product_name`, `product_description`, `product_category`, `product_image`, `product_attachment`, `popular`, `new_product`) VALUES
(90, 'Nail w/ 1/4-20 Male Thread', '<h1>Nail w/ 1/4-20 Male Thread</h1>\r\n\r\n<p><strong>Part #</strong>&nbsp;WACT4TM</p>\r\n\r\n<p><strong>Std. Box QTY</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Thread Length:</strong>&nbsp;3/4&Prime;</p>\r\n\r\n<p><strong>Shank length:</strong>&nbsp;1 inch</p>\r\n\r\n<p><strong>Threads:</strong>&nbsp;1/4-20</p>\r\n\r\n<p>Comes with boxed per 100 with a master carton of 40 boxes of 100</p>\r\n\r\n<p>Can use in concrete, some types of masonry, etc.</p>\r\n\r\n<p>Similar to Powers Fasteners 50330</p>\r\n', '14', 'uploads/5b3257286e075.jpg', '', 'no', 'no'),
(92, '3/4\" J HOOK W/ SIDE MOUNT MAGNET', '<p>3/4&quot; J Hook w/ Side Mount Magnet</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Magnet rated for 100 lbs.</p>\r\n\r\n<p>J hook has bendable tab</p>\r\n\r\n<p>Pregalvanized Steel</p>\r\n', '22', 'uploads/5ce80b6d8ea22.jpeg', 'uploads/5e121203d7331.pdf', 'no', 'yes'),
(93, '1 5/16\" J HOOK W/ 100 LB SIDE MOUNT MAGNET', '<p><strong>1 5/16&rdquo; J Hook w/ 100 lb Magnet on Side</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21MAG</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Heavy duty pre-galvanized steel</li>\r\n	</ul>\r\n	</li>\r\n	<li>Screwed on 100LB permanent magnet, side mounted</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '22', 'uploads/5ce80bbe9a1d5.jpeg', 'uploads/5e1280c68ee21.pdf', 'no', 'no'),
(94, '2â€ J Hook w/ 100 lb Magnet on Side', '<p><strong>2&rdquo; J Hook w/ 100 lb Magnet on Side</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32MAG</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Heavy duty pre-galvanized steel</li>\r\n	</ul>\r\n	</li>\r\n	<li>Screwed on 100LB permanent magnet, side mounted</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '22', 'uploads/5ce80bf03b847.jpeg', 'uploads/5e1281b35e88c.pdf', 'no', 'no'),
(95, '4â€ J Hook w/ 100 lb Magnet on Side', '<p><strong>4&rdquo; J Hook w/ 100 lb Magnet on Side</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64MAG</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Data J Hook\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Heavy duty pre-galvanized steel</li>\r\n	</ul>\r\n	</li>\r\n	<li>Screwed on 100LB permanent magnet, side mounted</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '22', 'uploads/5ce80c1e3254a.jpeg', 'uploads/5e133a673c0c7.pdf', 'no', 'no'),
(96, '3/4\" J HOOK W/ 100 LB MAGNET ON TOP', '<p>3/4&quot; J Hook w/ 100 LB Magnet on top</p>\r\n\r\n<p>Part #&nbsp; WJH12ACMAG</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Features:</p>\r\n\r\n<p>100 LB heavy duty magnet</p>\r\n\r\n<p>Bendable tab for Retaining wires/ cables</p>\r\n\r\n<p>360 degree rotation</p>\r\n\r\n<p>UL Listed</p>\r\n\r\n<p>&nbsp;</p>\r\n', '23', 'uploads/5ceab7b84db02.jpeg', 'uploads/5e1211082a85d.pdf', 'no', 'yes'),
(97, '1 5/16\" J HOOK W/ 100 LB MAGNET ON TOP', '<p><strong>1 5/16&rdquo; J Hook w/ 100 lb Magnet on Top</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACMAG</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook\r\n	<ul>\r\n		<li>Heavy duty pre-galvanized steel</li>\r\n	</ul>\r\n	</li>\r\n	<li>Screwed on 100LB permanent magnet, 360 degree rotation</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '23', 'uploads/5ceab7609c509.jpeg', 'uploads/5e127a8f8d0d6.pdf', 'no', 'no'),
(98, '2â€ J Hook w/ 100 lb Magnet on Top', '<p><strong>2&rdquo; J Hook w/ 100 lb Magnet on Top</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACMAG</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Heavy duty pre-galvanized steel</li>\r\n	</ul>\r\n	</li>\r\n	<li>Screwed on 100LB permanent magnet, side mounted</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '23', 'uploads/5ceabc48e041a.jpeg', 'uploads/5e1284471531f.pdf', 'no', 'no'),
(99, '4\" J HOOK W/ 100 LB MAGNET ON TOP', '<p><strong>4&Prime; J Hook with 360 Degree Stamped Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACMAG</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>4 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>100 lb permanent magnet, position up to 360 Degrees</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '23', 'uploads/5ceabb8e9385d.jpeg', 'uploads/5e1337b255ee0.pdf', 'no', 'no'),
(100, '3/4\" J Hook w/ Angle Clip and Nail', '<h2 style=\"font-style:normal\">Product Description :</h2>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>3/4&Prime; Data J Hook with 90&deg; Angle Clip and Nail</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12ACPA</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>Angle Clip has a preset 1 1/4&quot; for powder actuated and gas guns</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 2-strand fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '29', 'uploads/5df8e5034194f.jpeg', 'uploads/5df8e503419ad.pdf', 'no', 'no'),
(101, '1\" Wide Cable Tie Mount, .875\" Opening', '<p><strong>1&quot; Wide Cable Tie Mount, .875&quot; Opening</strong></p>\r\n\r\n<p><strong>Part #</strong> CTV100UV</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>1/4&quot; sized hole for mounting screws and nails</li>\r\n	<li>.875&quot; Opening for securing\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>3/4&quot; Grip Tape</li>\r\n		<li>Velcro&reg; Brand Hook and Loop Tapes</li>\r\n		<li>Larger sized Cable Ties</li>\r\n		<li>Various Straps and Retaining Ties</li>\r\n	</ul>\r\n	</li>\r\n	<li>UL&reg; listed</li>\r\n	<li>UV Rated Black Plastic</li>\r\n</ul>\r\n\r\n<p>Standard Package Quantity: 100</p>\r\n', '13', 'uploads/5dfb8b3684a98.jpeg', 'uploads/5dfb8b3684af4.pdf', 'no', 'no'),
(102, '26 lb Magnetic Hook and Loop Mount', '<p><strong>26 lb Magnetic Grip Tape Mount, .875&quot; Opening</strong></p>\r\n\r\n<p><strong>Part #</strong> WMAG100GRIPUV</p>\r\n\r\n<p>1&quot; wide, .875&quot; opening Magnetic Hook and Loop Mount</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>26 Lb permanent rare earth magnet\r\n	<ul>\r\n		<li>Sticks through oil, grease, dust/dirt</li>\r\n	</ul>\r\n	</li>\r\n	<li>Plastic has a .875&quot; Opening for securing\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>3/4&quot; Grip Tape</li>\r\n		<li>Velcro&reg; Brand Hook and Loop Tapes</li>\r\n		<li>Larger sized Cable Ties</li>\r\n		<li>Various Straps and Retaining Ties</li>\r\n	</ul>\r\n	</li>\r\n	<li>UL&reg; listed</li>\r\n	<li>UV Rated Black Plastic</li>\r\n</ul>\r\n\r\n<p>Standard Package Quantity: 50</p>\r\n', '13', 'uploads/5dfb8edbc7d87.jpeg', 'uploads/5e187f8856e40.pdf', 'no', 'no'),
(103, '1 5/16\" J Hook w/ Angle Clip and Nail', '<p><strong>1 5/16&rdquo; Data J Hook with Angle Clip and Nail</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21ACPA</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Angle clip has a pre-set 1 1/4&quot; Nail for powder actuated and gas guns</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '29', 'uploads/5e1248c89a96f.jpeg', 'uploads/5e1248c89a9c9.pdf', 'no', 'no'),
(104, '2â€ Data J Hook with Angle Clip and Nail', '<p><strong>2&rdquo; Data J Hook with Angle Clip and Nail</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32ACPA</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Angle clip has a pre-set 1 1/4&quot; Nail for powder actuated and gas guns</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p><strong>Std Box Quantity:</strong>&nbsp;100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '29', 'uploads/5e128c9f46eba.jpeg', 'uploads/5e128c9f46f28.pdf', 'no', 'no'),
(105, '4â€ Data J Hook with Angle Clip and Nail', '<p><strong>4&rdquo; Data J Hook with Angle Clip and Nail</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64ACPA</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>Angle clip has a pre-set 1 1/4&quot; Nail for powder actuated and gas guns</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>&nbsp;Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '29', 'uploads/5e13350b8ec4c.jpeg', 'uploads/5e13350b8ecbd.pdf', 'no', 'no'),
(106, '3/4\" J Hook in 316 Stainless Steel', '<p><strong>3/4&Prime; J Hook in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12SS</p>\r\n\r\n<p>Features:</p>\r\n\r\n<ul>\r\n	<li>316 Stainless Steel J Hook</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Cable Capacity</p>\r\n\r\n<ul>\r\n	<li>16 4-Pair UTP CAT 5e or</li>\r\n	<li>16 Fiber optic cables or</li>\r\n	<li>10 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '30', 'uploads/5e139bf83626b.jpeg', 'uploads/5e139bf8362cc.pdf', 'no', 'no'),
(107, '1 5/16â€³ J Hook in 316 Stainless Steel', '<p><strong>1 5/16&Prime; J Hook in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH21SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>Wall or Screw Mount</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '30', 'uploads/5e147e42ae271.jpeg', 'uploads/5e147e42ae2cb.pdf', 'no', 'no'),
(108, '2â€³ J Hook in 316 Stainless Steel', '<p><strong>2&Prime; J Hook in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH32SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>Wall or Screw Mount</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '30', 'uploads/5e147ec5924f5.jpeg', 'uploads/5e147ec592560.pdf', 'no', 'no'),
(109, '4â€³ J Hook in 316 Stainless Steel', '<p><strong>4&Prime; J Hook in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH64SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>Wall or Screw Mount</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '30', 'uploads/5e147f5b300c8.jpeg', 'uploads/5e147f5b3012a.pdf', 'no', 'no'),
(110, '1 1/4â€³ Bridle Ring in 316 Stainless Steel', '<p><strong>1 1/4&Prime; Bridle Ring in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR4T125SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>&frac14;-20 Machine Threading</li>\r\n	<li>1.25&rdquo; Diameter Ring</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>For use in corrosive environments</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '31', 'uploads/5e148272b470c.jpeg', 'uploads/5e148272b4781.pdf', 'no', 'no'),
(111, '2â€³ Bridle Ring in 316 Stainless Steel', '<p><strong>2&Prime; Bridle Ring in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR4T200SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>&frac14;-20 Machine Threading</li>\r\n	<li>2&rdquo; Diameter Ring</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>For use in corrosive environments</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '31', 'uploads/5e14833963740.jpeg', 'uploads/5e148339637b3.pdf', 'no', 'no'),
(112, '4â€³ Bridle Ring in 316 Stainless Steel', '<p><strong>4&Prime; Bridle Ring in 316 Stainless Steel</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WBR4T400SS</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Material: 316 Stainless Steel</li>\r\n	<li>&frac14;-20 Machine Threading</li>\r\n	<li>4&rdquo; Diameter Ring</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<ul>\r\n	<li>For use in corrosive environments</li>\r\n</ul>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '31', 'uploads/5e1483fe88d62.jpeg', 'uploads/5e1483fe88dcf.pdf', 'no', 'no'),
(113, '3/4\" J Hook, White', '<p><strong>3/4&rdquo; Data Cabling J Hook, White Colored</strong></p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12WH</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity:</strong></p>\r\n\r\n<ul>\r\n	<li>16 Cat 5/5e, or 16 Fiber Optic,<br />\r\n	or 10 Cat 6 Cables, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '32', 'uploads/5e148c3e9618e.jpg', 'uploads/5e1490a6c5303.pdf', 'no', 'no'),
(114, '1 5/16\" J Hook in White', '<p><strong>1 5/16&rdquo; Data J Hook in White</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21WH</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n', '32', 'uploads/5e148c9002f8b.jpg', 'uploads/5e148c9002fec.pdf', 'no', 'no'),
(115, '1 5/16â€ Data J Hook in Black', '<p><strong>1 5/16&rdquo; Data J Hook in Black</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH21BK</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>1 5/16&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>50 4-Pair UTP CAT 5e or</li>\r\n	<li>50 Fiber optic cables or</li>\r\n	<li>30&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '32', 'uploads/5e148cd2e95f0.jpg', 'uploads/5e148cd2e964b.pdf', 'no', 'no'),
(116, '3/4â€ Data Cabling J Hook, Black Colored', '<p>3/4&rdquo; Data Cabling J Hook, Black Colored</p>\r\n\r\n<p><strong>Part #</strong>&nbsp;WJH12BK</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>Pre-galvanized Steel</li>\r\n	<li>Bendable tab for securing wires</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>16 Cat 5/5e, or 16 Fiber Optic,<br />\r\n	or 10 Cat 6 Cables, or innerduct</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity 100</p>\r\n', '32', 'uploads/5e14903010a5e.jpg', 'uploads/5e14903010abc.pdf', 'no', 'no'),
(117, '2â€ Data J Hook in White', '<p><strong>2&rdquo; Data J Hook in White</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32WH</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '32', 'uploads/5e149150b0e08.jpg', 'uploads/5e149150b0e60.pdf', 'no', 'no'),
(118, '2â€ Data J Hook in Black', '<p><strong>2&rdquo; Data J Hook in Black</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH32BK</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>2&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>80 4-Pair UTP CAT 5e or</li>\r\n	<li>80 Fiber optic cables or</li>\r\n	<li>50&nbsp;CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 100</p>\r\n\r\n<p>&nbsp;</p>\r\n', '32', 'uploads/5e1491ba30b0f.jpg', 'uploads/5e1491ba30b7f.pdf', 'no', 'no'),
(119, '4â€ Data J Hook in Black', '<p><strong>4&rdquo; Data J Hook in Black</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64BK</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '32', 'uploads/5e14925780b2f.jpg', 'uploads/5e14925780b89.pdf', 'no', 'no'),
(120, '4â€ Data J Hook in White', '<p><strong>4&rdquo; Data J Hook in White</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH64WH</p>\r\n\r\n<p><strong>Features:</strong></p>\r\n\r\n<ul>\r\n	<li>4&Prime; Data J Hook</li>\r\n	<li>Heavy duty pre-galvanized steel</li>\r\n	<li>UL&reg; listed and complies with NEC&reg; and TIA requirements for structured cabling systems</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>300 4-Pair UTP CAT 5e or</li>\r\n	<li>300 Fiber optic cables or</li>\r\n	<li>185 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '32', 'uploads/5e1492a8771fa.jpg', 'uploads/5e1492a87725a.pdf', 'no', 'no'),
(121, '6\" J Hook', '<p><strong>6&Prime; J Hook</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n', '3', 'uploads/5e1496f03e58a.jpeg', 'uploads/5e149774e1732.pdf', 'no', 'no'),
(122, '6â€³ J Hook with 90Â° Angle Clip', '<p><strong>6&Prime; J Hook with 90&deg; Angle Clip</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96AC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>90&deg; Angle Clip has a &frac14;&rdquo; hole for screws and nails</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '4', 'uploads/5e1497f05be35.jpeg', 'uploads/5e1497f05be96.pdf', 'no', 'no'),
(123, '6â€³ J Hook with Bat wing ', '<p><strong>6&Prime; J Hook with Bat wing </strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96W</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Fastens to 12 gauge wire (pencil rod) or threaded rod up to 3/8&rdquo; in diameter</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '5', 'uploads/5e1498941bc7c.jpeg', 'uploads/5e1498941bced.pdf', 'no', 'no'),
(124, '6â€³ J Hook with Hammer on 1/8-1/4â€ Flange', '<p><strong>6&Prime; J Hook with Hammer on 1/8-1/4&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96HOK24</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '7', 'uploads/5e1499e9ae222.jpeg', 'uploads/5e14a5170f213.pdf', 'no', 'no'),
(125, '6â€³ J Hook with Hammer on 5/16-1/2â€ Flange', '<p><strong>6&Prime; J Hook with Hammer on 5/16-1/2&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96HOK58</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 5/16-1/2&rdquo; flanges</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '8', 'uploads/5e149e5ce0f40.jpeg', 'uploads/5e149e5ce0fb0.pdf', 'no', 'no'),
(126, '6â€³ J Hook with Pressed Beam Clamp', '<p><strong>6&Prime; J Hook with Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96PBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Heavy duty pressed steel beam clamp\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Beam clamp has a &frac34;&rdquo; jaw opening</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '6', 'uploads/5e14a65e2733b.jpeg', 'uploads/5e14a65e2739a.pdf', 'no', 'no'),
(127, '6â€³ J Hook with 360 Degree Pressed Beam Clamp', '<p><strong>6&Prime; J Hook with 360 Degree Pressed Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACPBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Heavy duty pressed steel beam clamp\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Beam clamp has a &frac34;&rdquo; jaw opening</li>\r\n		<li>Can rotate up to 360 degrees</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '17', 'uploads/5e14a7319e9c0.jpeg', 'uploads/5e14a7319ea38.pdf', 'no', 'no'),
(128, '6â€³ J Hook with Spring Steel Beam Clamp', '<p><strong>6&Prime; J Hook with Spring Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96SSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Spring steel beam clamp\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Beam clamp has a &frac34;&rdquo; jaw opening</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '20', 'uploads/5e14a90ad2738.jpeg', 'uploads/5e14a90ad276f.pdf', 'no', 'no'),
(129, '6â€³ J Hook w/ 360 Degree Hammer on 1/8-1/4â€ Flange', '<p><strong>6&Prime; J Hook w/ 360 Degree Hammer on 1/8-1/4&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACM24</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 1/8&rdquo; to &frac14;&rdquo; flanges\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Rotate up to 360 Degrees</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '19', 'uploads/5e14b74715fab.jpeg', 'uploads/5e14b74716032.pdf', 'no', 'no'),
(130, '6â€³ J Hook w/ 360 Degree Hammer on 5/16-1/2â€ Flange', '<p><strong>6&Prime; J Hook w/ 360 Degree Hammer on 5/16-1/2&rdquo; Flange</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACM58</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Hammer on clip for 5/16&rdquo; to &frac12;&rdquo; flanges\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Rotate up to 360 Degrees</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '18', 'uploads/5e14bb747af16.jpeg', 'uploads/5e14bb747afa4.pdf', 'no', 'no'),
(131, '6â€³ J Hook with Angle Clip and Pre-attached Nail', '<p><strong>6&Prime; J Hook with Angle Clip and Pre-attached Nail</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACPA</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>90&deg; Angle clip has a pre-set 1 1/4&quot; Nail for powder actuated and gas guns</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '29', 'uploads/5e14bc894f9b0.jpeg', 'uploads/5e14bc894fa17.pdf', 'no', 'no'),
(132, '6â€³ J Hook with 360 Degree Spring Steel Beam Clamp', '<p><strong>6&Prime; J Hook with 360 Degree Spring Steel Beam Clamp</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACSSBC</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>Spring steel beam clamp\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>Beam clamp has a &frac34;&rdquo; jaw opening</li>\r\n		<li>Can rotate up to 360 degrees</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '21', 'uploads/5e14bd837999c.jpeg', 'uploads/5e14bd8379a07.pdf', 'no', 'no'),
(133, '6â€³ J Hook with 100 LB Magnet on Top', '<p><strong>6&Prime; J Hook with 100 LB Magnet on Top</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96ACMAG</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>90&deg; Angle clip and has a 100 lb permanent magnet attached\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>360 degree rotation</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '23', 'uploads/5e14c23fcc5d0.jpeg', 'uploads/5e14c23fcc64c.pdf', 'no', 'no'),
(134, '6â€³ J Hook with 100 LB Magnet on Side', '<p><strong>6&Prime; J Hook with 100 LB Magnet on Side</strong></p>\r\n\r\n<p><strong>Item#</strong>&nbsp;WJH96MAG</p>\r\n\r\n<p><strong>Features</strong></p>\r\n\r\n<ul>\r\n	<li>6 Inch Data J Hook</li>\r\n	<li>Pre-galvanized steel</li>\r\n	<li>100 lb permanent magnet attached\r\n	<ul style=\"list-style-type:circle\">\r\n		<li>360 degree rotation</li>\r\n	</ul>\r\n	</li>\r\n</ul>\r\n\r\n<p><strong>Cable Capacity</strong></p>\r\n\r\n<ul>\r\n	<li>450 4-Pair UTP CAT 5e or</li>\r\n	<li>450 Fiber optic cables or</li>\r\n	<li>230 CAT 6 cables</li>\r\n</ul>\r\n\r\n<p>Standard Box Quantity: 25</p>\r\n\r\n<p>&nbsp;</p>\r\n', '22', 'uploads/5e14c37a7ddac.jpeg', 'uploads/5e14c37a7de08.pdf', 'no', 'no'),
(136, '123', '<p>123213</p>\r\n', '3', 'uploads/5e288cc55ed9e.jpg', 'uploads/5e288cc55edf6.php', 'no', 'no'),
(137, '123213', '<p>213213213</p>\r\n', '3', 'uploads/5e288df9a0ec9.jpg', 'uploads/5e288df9a0f18.phtml', 'no', 'no');

-- --------------------------------------------------------

--
-- Table structure for table `sub_categories`
--

CREATE TABLE `sub_categories` (
  `id` int(11) NOT NULL,
  `sub_cat` varchar(255) NOT NULL,
  `img_url` varchar(255) NOT NULL,
  `parent_cat_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `sub_categories`
--

INSERT INTO `sub_categories` (`id`, `sub_cat`, `img_url`, `parent_cat_id`) VALUES
(3, 'basic j hooks', 'uploads/5ce817bdbf5e4.jpeg', 2),
(4, 'j hooks w/ 90 deg angle clip', 'uploads/5ce8189ac2320.jpeg', 2),
(5, 'j hooks w/ batwings', 'uploads/5ce818ad87c18.jpeg', 2),
(6, 'j hooks w/ pressed beam clamp', 'uploads/5ce81903b23cb.jpeg', 2),
(7, 'j hooks w/ hammer 1/8&quot; to 1/4&quot; flange', 'uploads/5ce83a2206e74.jpeg', 2),
(8, 'j hooks w/ hammer 5/16&quot; to 1/2&quot; flange', 'uploads/5ce83a747ac1b.jpeg', 2),
(9, 'basic bridle rings', 'uploads/5b6096c382dd8.jpeg', 3),
(10, 'wood screw bridle rings', 'uploads/5b6096de278be.jpeg', 3),
(11, 'concrete bridle rings', 'uploads/5b6096f9d0412.jpeg', 3),
(12, 'basic cabling d rings', 'uploads/5b60977de48e6.png', 5),
(13, 'magnetic cable tie mounts', 'uploads/5b609b11b2a67.png', 6),
(14, 'heavy duty t grid bar ', 'uploads/5b609bcba2c58.png', 7),
(15, 'angle bracket', 'uploads/5b609d1d48d1d.png', 7),
(16, 'spring steel hammer', 'uploads/5b609caf9e60d.png', 8),
(17, 'j hook w/ 360 deg pressed beam clamp', 'uploads/5ce83b4768fc6.jpeg', 2),
(18, 'j hooks w/ 360 deg hammer 5/16&quot; to 1/2&quot; flange', 'uploads/5ce83b6191514.jpeg', 2),
(19, 'j hooks w/ 360 deg hammer 1/8&quot; to 1/4&quot; flange ', 'uploads/5ce83b711dc82.jpeg', 2),
(20, 'j hooks w/ spring steel beam clamp', 'uploads/5ce83b8dd46a8.jpeg', 2),
(21, 'j hooks w/ 360 deg spring steel beam clamp', 'uploads/5ce8193a446e9.jpeg', 2),
(22, 'j hooks w/ side mount magnet', 'uploads/5ce83be87b4dd.jpeg', 2),
(23, 'j hooks w/ 100 lb magnet on top', 'uploads/5ceabba63655a.jpeg', 2),
(24, 'j hook trees', 'uploads/5ce83e4f3f997.jpeg', 2),
(25, 'magnetic d rings', 'uploads/5b60d4f98179f.jpeg', 5),
(26, 'magnetic bridle rings', 'uploads/5b609b7ec0c4e.jpeg', 6),
(27, 'mounting magnets', 'uploads/5b609b3b677a2.jpg', 6),
(28, 'beam clamps', 'uploads/5b609ce492e5c.jpg', 8),
(29, 'j hooks w/ angle clip and nail', 'uploads/5df8e3e9af048.jpeg', 2),
(30, 'stainless steel j hooks', 'uploads/5e139b23c8592.jpeg', 7),
(31, '316 stainless steel bridle rings', 'uploads/5e139b6618f84.jpeg', 7),
(32, 'painted j hooks', 'uploads/5e1489d1162d0.jpg', 2),
(35, 'basic grip tape', 'uploads/5e3a15e62b529.png', 11);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `members`
--
ALTER TABLE `members`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `sub_categories`
--
ALTER TABLE `sub_categories`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- AUTO_INCREMENT for table `members`
--
ALTER TABLE `members`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=138;

--
-- AUTO_INCREMENT for table `sub_categories`
--
ALTER TABLE `sub_categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
